// src/agents/codewriter.ts
//
// Generates Screen and Task classes per plan entries,
// derived 100% from plan + actions — no hardcoded names.
// Supports full Testla Action spectrum and strictly separates Tasks from Assertions.

import type { AnalystPlan, Intention } from "./analyst.ts";
import type { ExecutedAction } from "./playwright_cli.ts";
import { logger } from "../utils/logger.ts";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ResolvedElement {
  constName: string;
  semanticLabel: string;
  locatorCode: string;
  kind: string; // 'click', 'fill', 'hover', 'type', 'assert', 'navigate', etc.
  screenClass: string;
  fillValue?: string;
  assertionKind?: string;
  assertionValue?: string;
  assertionCount?: number;
}

export interface ScreenFile {
  className: string;
  path: string;
  content: string;
}

export interface TaskFile {
  className: string;
  path: string;
  content: string;
}

export interface GeneratedFiles {
  screenFiles: ScreenFile[];
  screensIndex: { path: string; content: string };
  taskFiles: TaskFile[];
  tasksIndex: { path: string; content: string };
  testFile: { path: string; content: string };
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function toScreamingSnakeCase(label: string): string {
  return label
    .trim()
    .replace(/[^a-zA-Z0-9\s]/g, "")
    .replace(/\s+/g, "_")
    .toUpperCase();
}

function toCamelCase(label: string): string {
  return label
    .trim()
    .replace(/[^a-zA-Z0-9\s]/g, "")
    .toLowerCase()
    .replace(/\s+(\w)/g, (_, c: string) => c.toUpperCase());
}

function toPascalCase(label: string): string {
  const camel = toCamelCase(label);
  return camel.charAt(0).toUpperCase() + camel.slice(1);
}

function generateBarrelFile(classNames: string[]): string {
  const imports = classNames
    .map((name) => `import { ${name} } from './${name}';`)
    .join("\n");

  const exports = classNames
    .map((name) => `  ${name}`)
    .join(",\n");

  return [
    `// Auto-generated by Testla CodeWriter`,
    imports,
    `export {`,
    exports,
    `};`,
  ].join("\n");
}

// ─── Mapping Actions to Testla Code ───────────────────────────────────────────

function getActionCode(el: ResolvedElement, paramName?: string): string {
  const ref = `${el.screenClass}.${el.constName}`;
  const val = paramName
    ? `this.${paramName}`
    : el.fillValue
    ? `"${el.fillValue}"`
    : '""';

  switch (el.kind.toLowerCase()) {
    case "click":       return `Click.on(${ref})`;
    case "doubleclick": return `DoubleClick.on(${ref})`;
    case "fill":        return `Fill.in(${ref}).with(${val})`;
    case "type":        return `Type.in(${ref}).fillWith(${val})`;
    case "hover":       return `Hover.over(${ref})`;
    case "check":       return `Check.on(${ref})`;
    case "remove":      return `Remove.from(${ref})`;
    case "select":      return `Select.option(${val}).from(${ref})`;
    case "press":       return `Press.key(${val})`;
    case "clear":       return `Clear.fill(${ref})`;
    default:            return `Click.on(${ref})`;
  }
}

// ─── Core Logic ───────────────────────────────────────────────────────────────

function buildElementToScreenMap(plan: AnalystPlan): Map<string, string[]> {
  const map = new Map<string, string[]>();
  for (const screen of plan.screens ?? []) {
    const className = toPascalCase(screen.name);
    for (const elementLabel of screen.elements ?? []) {
      const key = elementLabel.toLowerCase();
      const existing = map.get(key) ?? [];
      existing.push(className);
      map.set(key, existing);
    }
  }
  return map;
}

export function buildResolvedElements(
  plan: AnalystPlan,
  actions: ExecutedAction[],
): ResolvedElement[] {
  const elementToScreens = buildElementToScreenMap(plan);
  const cursor = new Map<string, number>();

  const interactiveIntentions: Intention[] = plan.intentions.filter(
    (i) => i.action !== "navigate",
  );
  const interactiveActions: ExecutedAction[] = actions.filter(
    (a) => a.kind !== "navigate" && a.kind !== "snapshot",
  );

  return interactiveIntentions.map((intention, idx) => {
    const action = interactiveActions[idx];
    if (!action) {
      throw new Error(
        `[CodeWriter] Misalignment: intention "${intention.target}" has no corresponding action.`,
      );
    }

    const key = intention.target.toLowerCase();
    const screens = elementToScreens.get(key) ?? [];
    const used = cursor.get(key) ?? 0;

    const screenClass =
      screens[used] ??
      toPascalCase(plan.screens?.at(-1)?.name ?? "GeneratedScreen");

    cursor.set(key, used + 1);

    return {
      constName: toScreamingSnakeCase(intention.target),
      semanticLabel: intention.target,
      locatorCode: action.locatorCode!,
      kind: intention.action,
      screenClass,
      fillValue: intention.value,
      assertionKind:  intention.assertionKind,
      assertionValue: intention.assertionValue,
      assertionCount: intention.assertionCount,
    };
  });
}

// ─── Fixture Patching ─────────────────────────────────────────────────────────
function buildFixtureEntry(
  actorVar: string,
  hasCredentials: boolean,
): { typeEntry: string; fixtureEntry: string } {
  const envPrefix = actorVar.toUpperCase();

  const typeEntry = `  ${actorVar}: Actor;`;

  const credArgs = hasCredentials
    ? `\`\${process.env.${envPrefix}_USER_NAME}\`,\n      \`\${process.env.${envPrefix}_USER_PASSWORD}\``
    : `"",\n      ""`;

  const fixtureEntry = [
    `  ${actorVar}: async ({ browser }, use) => {`,
    `    const ${actorVar} = await createUser(`,
    `      browser,`,
    `      "${actorVar}",`,
    `      ${credArgs},`,
    `    );`,
    `    await use(${actorVar});`,
    `  },`,
  ].join("\n");

  return { typeEntry, fixtureEntry };
}

export async function updateFixtureFile(
  projectDir: string,
  persona: string,
  credentials?: { username: string; password: string },
): Promise<void> {
  const fixturePath = `${projectDir}/fixtures/user.ts`;
  const actorVar    = persona.replace(/\s+/g, "_");

  let content: string;
  try {
    content = await Deno.readTextFile(fixturePath);
  } catch {
    throw new Error(`[CodeWriter] Fixture not found at ${fixturePath}`);
  }

  // Bereits vorhanden? → nichts tun
  if (content.includes(`${actorVar}:`)) {
    logger.info("CodeWriter", `⏭️  Fixture: "${actorVar}" already present — skipping.`);
    return;
  }

  const { typeEntry, fixtureEntry } = buildFixtureEntry(actorVar, !!credentials);

  // ── Insertion Point 1: Actors type block ────────────────────────────────────
  // Sucht "type Actors = {" und fügt vor dem schließenden "}" ein
  const typeBlockRegex = /(type Actors\s*=\s*\{[^}]*)(\})/;
  if (!typeBlockRegex.test(content)) {
    throw new Error(`[CodeWriter] Could not find "type Actors" block in fixture.`);
  }
  content = content.replace(typeBlockRegex, `$1  ${typeEntry}\n$2`);

  // ── Insertion Point 2: test.extend block ────────────────────────────────────
  // Sucht das letzte "}," vor der abschließenden "});" und fügt danach ein
  const extendCloseRegex = /([ \t]*\},\s*\n)(}\);)/;
  if (!extendCloseRegex.test(content)) {
    throw new Error(`[CodeWriter] Could not find closing of test.extend block in fixture.`);
  }
  content = content.replace(extendCloseRegex, `$1${fixtureEntry}\n$2`);

  await Deno.writeTextFile(fixturePath, content);
  logger.info("CodeWriter", `✅ Fixture: added "${actorVar}" to ${fixturePath}`);

  // ── .env Update (nur wenn Credentials mitgegeben) ───────────────────────────
  if (credentials) {
    await updateEnvFile(projectDir, actorVar, credentials);
  }
}

async function updateEnvFile(
  projectDir: string,
  actorVar: string,
  credentials: { username: string; password: string },
): Promise<void> {
  const envPath    = `${projectDir}/.env`;
  const envPrefix  = actorVar.toUpperCase();
  const nameKey    = `${envPrefix}_USER_NAME`;
  const passKey    = `${envPrefix}_USER_PASSWORD`;

  let existing = "";
  try {
    existing = await Deno.readTextFile(envPath);
  } catch {
    // .env existiert noch nicht — wird neu erstellt
  }

  const lines: string[] = existing.length > 0 ? existing.split("\n") : [];
  let changed = false;

  if (!existing.includes(nameKey)) {
    lines.push(`${nameKey}=${credentials.username}`);
    changed = true;
  }
  if (!existing.includes(passKey)) {
    lines.push(`${passKey}=${credentials.password}`);
    changed = true;
  }

  if (changed) {
    await Deno.writeTextFile(envPath, lines.join("\n") + "\n");
    logger.info("CodeWriter", `✅ .env: added ${nameKey} + ${passKey}`);
  }
}

// ─── Task Assignment ──────────────────────────────────────────────────────────
//
// Maps plan.tasks[n].intentionIndices → ResolvedElement[].
//
// Navigate intentions assigned to a task (ASSIGN TO TASK rule) are converted
// to synthetic elements so generateTaskFile can emit Navigate.to(...).
// Assert intentions are always excluded — they belong in the test body.

function assignElementsToTasks(
  plan: AnalystPlan,
  elements: ResolvedElement[],
): Map<string, ResolvedElement[]> {
  const result = new Map<string, ResolvedElement[]>();
  if (!plan.tasks || plan.tasks.length === 0) return result;

  // Build reverse-lookup: absolute intention index → position in elements[]
  // (elements[] contains only non-navigate intentions, 1:1 with interactiveActions)
  const absToElementIdx = new Map<number, number>();
  let elementPtr = 0;
  for (let i = 0; i < plan.intentions.length; i++) {
    if (plan.intentions[i].action !== "navigate") {
      absToElementIdx.set(i, elementPtr++);
    }
  }

  for (const task of plan.tasks) {
    const className = toPascalCase(task.name);
    const taskElements: ResolvedElement[] = [];

    for (const absIdx of task.intentionIndices ?? []) {
      const intention = plan.intentions[absIdx];
      if (!intention) continue;

      if (intention.action === "navigate") {
        // Synthetic element — no locator, no screen class needed.
        // fillValue carries the URL so getActionCode / generateTaskFile
        // can emit Navigate.to("<url>") correctly.
        taskElements.push({
          constName: "NAVIGATE",
          semanticLabel: intention.target,
          locatorCode: "",
          kind: "navigate",
          screenClass: "",
          fillValue: intention.target,
        });
      } else {
        const elIdx = absToElementIdx.get(absIdx);
        // Assertions are excluded: they stay in the test body.
        if (
          elIdx !== undefined &&
          elements[elIdx] &&
          elements[elIdx].kind !== "assert"
        ) {
          taskElements.push(elements[elIdx]);
        }
      }
    }

    result.set(className, taskElements);
  }

  return result;
}

// ─── File Generators ──────────────────────────────────────────────────────────

function generateScreenFile(
  className: string,
  elements: ResolvedElement[],
): string {
  const seen = new Set<string>();
  const unique = elements.filter((el) => {
    if (seen.has(el.constName)) return false;
    seen.add(el.constName);
    return true;
  });

  const statics = unique
    .map(
      (el) =>
        `  /** ${el.semanticLabel} */\n` +
        `  static ${el.constName}: LazySelector = (page) =>\n` +
        `    ${el.locatorCode};`,
    )
    .join("\n\n");

  return [
    `// Auto-generated by Nova CodeWriter`,
    `// DO NOT EDIT MANUALLY`,
    ``,
    `import { LazySelector } from "@testla/screenplay-playwright/web/types";`,
    ``,
    `export class ${className} {`,
    statics,
    `}`,
    ``,
  ].join("\n");
}

function generateTaskFile(
  taskName: string,
  elements: ResolvedElement[],
): string {
  const className = toPascalCase(taskName);
  const factoryMethodName = toCamelCase(taskName);

  // Only value-bearing kinds become constructor parameters
  const paramElements = elements.filter((el) =>
    ["fill", "type", "select"].includes(el.kind),
  );
  const params = paramElements.map((el) => ({
    name: toCamelCase(el.semanticLabel),
    originalLabel: el.semanticLabel,
  }));

  const ctor =
    params.length > 0
      ? `private constructor(\n${params.map((p) => `    private ${p.name}: string,`).join("\n")}\n  )`
      : `private constructor()`;

  const factoryArgs = params.map((p) => `${p.name}: string`).join(", ");
  const factory = [
    `  public static ${factoryMethodName}(${factoryArgs}): ${className} {`,
    `    const instance = new ${className}(${params.map((p) => p.name).join(", ")});`,
    `    instance.setCallStackInitializeCalledWith({ ${params.map((p) => p.name).join(", ")} });`,
    `    return instance;`,
    `  }`,
  ].join("\n");

  // Collect required web action imports (navigate handled separately below)
  const webActionsList = [
    "Check", "Clear", "Click", "Count", "DoubleClick", "Download",
    "DragAndDrop", "Fill", "Get", "Hover", "Press", "Reload",
    "Remove", "Select", "Set", "Type", "Wait",
  ];
  const usedWeb = [
    ...new Set(
      elements
        .map((el) => {
          if (el.kind === "navigate") return "Navigate";
          return toPascalCase(el.kind);
        })
        .filter((k) => ["Navigate", ...webActionsList].includes(k)),
    ),
  ];
  if (usedWeb.length === 0 && elements.length > 0) usedWeb.push("Click");

  // Screen imports — navigate elements have no screenClass, skip them
  const usedScreenClasses = [
    ...new Set(elements.map((el) => el.screenClass).filter(Boolean)),
  ];
  const screenImports = usedScreenClasses
    .map((cls) => `import { ${cls} } from '../screens/${cls}';`)
    .join("\n");

  // performAs steps
  const steps = elements.map((el) => {
    if (el.kind === "navigate") {
      return `      Navigate.to("${el.fillValue}"),`;
    }
    const p = params.find((param) => param.originalLabel === el.semanticLabel);
    return `      ${getActionCode(el, p?.name)},`;
  });

  return [
    `// Auto-generated by Nova CodeWriter`,
    `// DO NOT EDIT MANUALLY`,
    ``,
    `import { Actor, Task } from '@testla/screenplay-playwright';`,
    `import { ${usedWeb.join(", ")} } from '@testla/screenplay-playwright/web';`,
    screenImports,
    ``,
    `export class ${className} extends Task {`,
    `  ${ctor} { super(); }`,
    ``,
    `  public async performAs(actor: Actor): Promise<any> {`,
    `    return actor.attemptsTo(`,
    ...steps,
    `    );`,
    `  }`,
    ``,
    factory,
    `}`,
    ``,
  ].join("\n");
}

function buildAssertionCode(el: ResolvedElement): string {
  const ref  = `${el.screenClass}.${el.constName}`;
  const kind = el.assertionKind ?? "visible";

  switch (kind) {
    case "visible":   return `Element.toBe.visible(${ref})`;
    case "enabled":   return `Element.toBe.enabled(${ref})`;
    case "checked":   return `Element.toBe.checked(${ref})`;
    case "text":      return `Element.toHave.text(${ref}, "${el.assertionValue ?? ""}")`;
    case "value":     return `Element.toHave.value(${ref}, "${el.assertionValue ?? ""}")`;
    case "count":     return `Element.toBe.count(${ref}, ${el.assertionCount ?? 1})`;
    case "minCount":  return `Element.toBe.minCount(${ref}, ${el.assertionCount ?? 1})`;
    case "url":       return `Page.toHave.url("${el.semanticLabel}")`;
    default:          return `Element.toBe.visible(${ref})`;
  }
}

function generateTestFile(
  plan: AnalystPlan,
  taskFiles: TaskFile[],
  elements: ResolvedElement[],
): string {
  const testName = plan.test?.name ?? "Generated Test";
  const persona  = plan.test?.persona ?? "Tester";
  const actorVar = persona.replace(/\s+/g, "_");
  const baseUrl  = plan.intentions.find((i) => i.action === "navigate")?.target ?? "/";

  const navigateIsInTask = plan.tasks?.some((t) =>
    (t.intentionIndices ?? []).some((i) => plan.intentions[i]?.action === "navigate"),
  ) ?? false;

  // ── Assertions aufteilen ────────────────────────────────────────────────────
  const assertElements = elements.filter((el) => el.kind === "assert");
  const urlAsserts     = assertElements.filter((el) => el.assertionKind === "url");
  const elemAsserts    = assertElements.filter((el) => el.assertionKind !== "url");

  // ── Web-Imports ─────────────────────────────────────────────────────────────
  const webImports: string[] = [];
  if (!navigateIsInTask)       webImports.push("Navigate");
  if (elemAsserts.length > 0)  webImports.push("Element");
  if (urlAsserts.length > 0)   webImports.push("Page");

  // ── Task + Screen Imports (Barrel) ──────────────────────────────────────────
  const taskImport = taskFiles.length > 0
    ? `import { ${taskFiles.map((t) => t.className).join(", ")} } from "../screenplay/tasks";`
    : "";

  const usedScreenClasses = [...new Set(elemAsserts.map((el) => el.screenClass))];
  const screenImport = usedScreenClasses.length > 0
    ? `import { ${usedScreenClasses.join(", ")} } from "../screenplay/screens";`
    : "";

  // ── attemptsTo Steps ────────────────────────────────────────────────────────
  const navigateStep  = !navigateIsInTask ? [`    Navigate.to("${baseUrl}"),`] : [];
  const taskCallLines = taskFiles.flatMap((t) => {
    const taskPlan   = plan.tasks?.find((p) => toPascalCase(p.name) === t.className);
    const fillValues = (taskPlan?.intentionIndices ?? [])
      .map((i) => plan.intentions[i])
      .filter((i) => ["fill", "type", "select"].includes(i?.action))
      .map((i) => `"${i.value ?? ""}"`)
      .join(", ");
    const factory = toCamelCase(taskPlan?.name ?? t.className);
    return [`    ${t.className}.${factory}(${fillValues}),`];
  });

  // ── actor.asks() Blöcke ─────────────────────────────────────────────────────
  const assertionCalls = assertElements.map((el) => {
    const question = buildAssertionCode(el);
    return `\n  await ${actorVar}.asks(\n    ${question},\n  );`;
  });

  return [
    `// Auto-generated by Testla CodeWriter`,
    ``,
    `import { test } from "../fixtures/user";`,
    ...(webImports.length > 0
      ? [`import { ${webImports.join(", ")} } from "@testla/screenplay-playwright/web";`]
      : []),
    ...(taskImport   ? [taskImport]   : []),
    ...(screenImport ? [screenImport] : []),
    ``,
    `test("${testName}", async ({ ${actorVar} }) => {`,
    `  await ${actorVar}.attemptsTo(`,
    ...navigateStep,
    ...taskCallLines,
    `  );`,
    ...assertionCalls,
    `});`,
    ``,
  ].join("\n");
}

// ─── Reporting ────────────────────────────────────────────────────────────────

function logMappingReport(elements: ResolvedElement[]): void {
  logger.info("CodeWriter", "────────────────── TOON MAPPING REPORT ──────────────────");
  for (const e of elements) {
    const icon = e.kind === "assert" ? "🔍" : e.kind === "navigate" ? "🌐" : "🖱️ ";
    logger.info("CodeWriter", `${icon} ${e.screenClass || "—"}.${e.constName} (${e.kind})`);
    logger.info("CodeWriter", `     Source: "${e.semanticLabel}"`);
  }
  logger.info("CodeWriter", "─────────────────────────────────────────────────────────");
}

// ─── Orchestration ────────────────────────────────────────────────────────────

export function generateScreenplayFiles(
  projectDir: string,
  plan: AnalystPlan,
  actions: ExecutedAction[],
): GeneratedFiles {
  const elements = buildResolvedElements(plan, actions);
  logMappingReport(elements);

  // Group elements by screen for Screen file generation
  const byScreen = new Map<string, ResolvedElement[]>();
  for (const el of elements) {
    if (!el.screenClass) continue; // navigate synthetics have no screen
    const group = byScreen.get(el.screenClass) ?? [];
    group.push(el);
    byScreen.set(el.screenClass, group);
  }

  const screenFiles: ScreenFile[] = [...byScreen.entries()].map(
    ([className, els]) => ({
      className,
      path: `${projectDir}/screenplay/screens/${className}.ts`,
      content: generateScreenFile(className, els),
    }),
  );

  const elementsByTask = assignElementsToTasks(plan, elements);
  const taskFiles: TaskFile[] = [...elementsByTask.entries()]
    .filter(([, els]) => els.length > 0)
    .map(([className, els]) => ({
      className,
      path: `${projectDir}/screenplay/tasks/${className}.ts`,
      content: generateTaskFile(
        plan.tasks.find((t) => toPascalCase(t.name) === className)?.name ??
          className,
        els,
      ),
    }));

  return {
    screenFiles,
    screensIndex: {
      path: `${projectDir}/screenplay/screens/index.ts`,
      content: generateBarrelFile(screenFiles.map((f) => f.className)),
    },
    taskFiles,
    tasksIndex: {
      path: `${projectDir}/screenplay/tasks/index.ts`,
      content: generateBarrelFile(taskFiles.map((f) => f.className)),
    },
    testFile: {
      path: `${projectDir}/tests/${toPascalCase(plan.test?.name ?? "Test")}.test.ts`,
      content: generateTestFile(plan, taskFiles, elements),
    },
  };
}

export async function writeScreenplayFiles(
  projectDir: string,
  plan: AnalystPlan,
  actions: ExecutedAction[],
): Promise<void> {
  const files = generateScreenplayFiles(projectDir, plan, actions);

  await Deno.mkdir(`${projectDir}/screenplay/screens`, { recursive: true });
  await Deno.mkdir(`${projectDir}/screenplay/tasks`, { recursive: true });
  await Deno.mkdir(`${projectDir}/tests`, { recursive: true });

  for (const f of files.screenFiles) {
    await Deno.writeTextFile(f.path, f.content);
    logger.info("CodeWriter", `✅ Screen: ${f.path}`);
  }
  await Deno.writeTextFile(files.screensIndex.path, files.screensIndex.content);
  logger.info("CodeWriter", `✅ Barrel: screens/index.ts`);

  for (const f of files.taskFiles) {
    await Deno.writeTextFile(f.path, f.content);
    logger.info("CodeWriter", `✅ Task:   ${f.path}`);
  }
  await Deno.writeTextFile(files.tasksIndex.path, files.tasksIndex.content);
  logger.info("CodeWriter", `✅ Barrel: tasks/index.ts`);

  await Deno.writeTextFile(files.testFile.path, files.testFile.content);
  logger.info("CodeWriter", `✅ Test:   ${files.testFile.path}`);

  await updateFixtureFile(projectDir, plan.test?.persona ?? "Tester");
  logger.info("CodeWriter", `✅ Fixture:  updated for persona "${plan.test?.persona ?? "Tester"}"`);
  logger.info("CodeWriter", "✅ Screenplay files generated");
}